<?
			if($PaisG1 == '1'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/1.gif>";}
			if($PaisG1 == '2'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/2.gif>";}
			if($PaisG1 == '3'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/3.gif>";}
			if($PaisG1 == '4'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/4.gif>";}
			if($PaisG1 == '5'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/5.gif>";}
			if($PaisG1 == '6'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/6.gif>";}
			if($PaisG1 == '7'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/7.gif>";}
			if($PaisG1 == '8'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/8.gif>";}
			if($PaisG1 == '9'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/9.gif>";}
			if($PaisG1 == '10'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/10.gif>";}
			if($PaisG1 == '11'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/11.gif>";}
			if($PaisG1 == '12'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/12.gif>";}
			if($PaisG1 == '13'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/13.gif>";}
			if($PaisG1 == '14'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/14.gif>";}
			if($PaisG1 == '15'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/15.gif>";}
			if($PaisG1 == '16'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/16.gif>";}
			if($PaisG1 == '17'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/17.gif>";}
			if($PaisG1 == '18'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/18.gif>";}
			if($PaisG1 == '19'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/19.gif>";}
			if($PaisG1 == '20'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/20.gif>";}
			if($PaisG1 == '21'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/21.gif>";}
			if($PaisG1 == '22'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/22.gif>";}
			if($PaisG1 == '23'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/23.gif>";}
			if($PaisG1 == '24'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/24.gif>";}
			if($PaisG1 == '25'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/25.gif>";}
			if($PaisG1 == '26'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/26.gif>";}
			if($PaisG1 == '27'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/27.gif>";}
			if($PaisG1 == '28'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/28.gif>";}
			if($PaisG1 == '29'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/29.gif>";}
			if($PaisG1 == '30'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/30.gif>";}
			if($PaisG1 == '31'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/31.gif>";}
			if($PaisG1 == '32'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/32.gif>";}
			if($PaisG1 == '33'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/33.gif>";}
			if($PaisG1 == '34'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/34.gif>";}
			if($PaisG1 == '35'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/35.gif>";}
			if($PaisG1 == '36'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/36.gif>";}
			if($PaisG1 == '37'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/37.gif>";}
			if($PaisG1 == '38'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/38.gif>";}
			if($PaisG1 == '39'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/39.gif>";}
			if($PaisG1 == '40'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/40.gif>";}
			if($PaisG1 == '41'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/41.gif>";}
			if($PaisG1 == '42'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/42.gif>";}
			if($PaisG1 == '43'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/43.gif>";}
			if($PaisG1 == '44'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/44.gif>";}
			if($PaisG1 == '45'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/45.gif>";}
			if($PaisG1 == '46'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/46.gif>";}
			if($PaisG1 == '47'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/47.gif>";}
			if($PaisG1 == '48'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/48.gif>";}
			if($PaisG1 == '49'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/49.gif>";}
			if($PaisG1 == '50'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/50.gif>";}
			if($PaisG1 == '51'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/51.gif>";}
			if($PaisG1 == '52'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/52.gif>";}
			if($PaisG1 == '53'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/53.gif>";}
			if($PaisG1 == '54'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/54.gif>";}
			if($PaisG1 == '55'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/55.gif>";}
			if($PaisG1 == '56'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/56.gif>";}
			if($PaisG1 == '57'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/57.gif>";}
			if($PaisG1 == '58'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/58.gif>";}
			if($PaisG1 == '59'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/59.gif>";}
			if($PaisG1 == '60'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/60.gif>";}
			if($PaisG1 == '61'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/61.gif>";}
			if($PaisG1 == '62'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/62.gif>";}
			if($PaisG1 == '63'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/63.gif>";}
			if($PaisG1 == '64'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/64.gif>";}
			if($PaisG1 == '65'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/65.gif>";}
			if($PaisG1 == '66'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/66.gif>";}
			if($PaisG1 == '67'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/67.gif>";}
			if($PaisG1 == '68'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/68.gif>";}
			if($PaisG1 == '69'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/69.gif>";}
			if($PaisG1 == '70'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/70.gif>";}
			if($PaisG1 == '71'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/71.gif>";}
			if($PaisG1 == '72'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/72.gif>";}
			if($PaisG1 == '73'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/73.gif>";}
			if($PaisG1 == '74'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/74.gif>";}
			if($PaisG1 == '75'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/75.gif>";}
			if($PaisG1 == '76'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/76.gif>";}
			if($PaisG1 == '77'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/77.gif>";}
			if($PaisG1 == '78'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/78.gif>";}
			if($PaisG1 == '79'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/79.gif>";}
			if($PaisG1 == '80'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/80.gif>";}
			if($PaisG1 == '81'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/81.gif>";}
			if($PaisG1 == '82'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/82.gif>";}
			if($PaisG1 == '83'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/83.gif>";}
			if($PaisG1 == '84'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/84.gif>";}
			if($PaisG1 == '85'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/85.gif>";}
			if($PaisG1 == '86'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/86.gif>";}
			if($PaisG1 == '87'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/87.gif>";}
			if($PaisG1 == '88'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/88.gif>";}
			if($PaisG1 == '89'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/89.gif>";}
			if($PaisG1 == '90'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/90.gif>";}
			if($PaisG1 == '91'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/91.gif>";}
			if($PaisG1 == '92'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/92.gif>";}
			if($PaisG1 == '93'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/93.gif>";}
			if($PaisG1 == '94'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/94.gif>";}
			if($PaisG1 == '95'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/95.gif>";}
			if($PaisG1 == '96'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/96.gif>";}
			if($PaisG1 == '97'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/97.gif>";}
			if($PaisG1 == '98'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/98.gif>";}
			if($PaisG1 == '99'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/99.gif>";}
			if($PaisG1 == '100'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/100.gif>";}
			if($PaisG1 == '101'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/101.gif>";}
			if($PaisG1 == '102'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/102.gif>";}
			if($PaisG1 == '103'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/103.gif>";}
			if($PaisG1 == '104'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/104.gif>";}
			if($PaisG1 == '105'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/105.gif>";}
			if($PaisG1 == '106'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/106.gif>";}
			if($PaisG1 == '107'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/107.gif>";}
			if($PaisG1 == '108'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/108.gif>";}
			if($PaisG1 == '109'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/109.gif>";}
			if($PaisG1 == '110'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/110.gif>";}
			if($PaisG1 == '111'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/111.gif>";}
			if($PaisG1 == '112'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/112.gif>";}
			if($PaisG1 == '113'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/113.gif>";}
			if($PaisG1 == '114'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/114.gif>";}
			if($PaisG1 == '115'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/115.gif>";}
			if($PaisG1 == '116'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/116.gif>";}
			if($PaisG1 == '117'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/117.gif>";}
			if($PaisG1 == '118'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/118.gif>";}
			if($PaisG1 == '119'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/119.gif>";}
			if($PaisG1 == '120'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/120.gif>";}
			if($PaisG1 == '121'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/121.gif>";}
			if($PaisG1 == '122'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/122.gif>";}
			if($PaisG1 == '123'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/123.gif>";}
			if($PaisG1 == '124'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/124.gif>";}
			if($PaisG1 == '125'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/125.gif>";}
			if($PaisG1 == '126'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/126.gif>";}
			if($PaisG1 == '127'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/127.gif>";}
			if($PaisG1 == '128'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/128.gif>";}
			if($PaisG1 == '129'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/129.gif>";}
			if($PaisG1 == '130'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/130.gif>";}
			if($PaisG1 == '131'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/131.gif>";}
			if($PaisG1 == '132'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/132.gif>";}
			if($PaisG1 == '133'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/133.gif>";}
			if($PaisG1 == '134'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/134.gif>";}
			if($PaisG1 == '135'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/135.gif>";}
			if($PaisG1 == '136'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/136.gif>";}
			if($PaisG1 == '137'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/137.gif>";}
			if($PaisG1 == '138'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/138.gif>";}
			if($PaisG1 == '139'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/139.gif>";}
			if($PaisG1 == '140'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/140.gif>";}
			if($PaisG1 == '141'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/141.gif>";}
			if($PaisG1 == '142'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/142.gif>";}
			if($PaisG1 == '143'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/143.gif>";}
			if($PaisG1 == '144'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/144.gif>";}
			if($PaisG1 == '145'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/145.gif>";}
			if($PaisG1 == '146'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/146.gif>";}
			if($PaisG1 == '147'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/147.gif>";}
			if($PaisG1 == '148'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/148.gif>";}
			if($PaisG1 == '149'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/149.gif>";}
			if($PaisG1 == '150'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/150.gif>";}
			if($PaisG1 == '151'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/151.gif>";}
			if($PaisG1 == '152'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/152.gif>";}
			if($PaisG1 == '153'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/153.gif>";}
			if($PaisG1 == '154'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/154.gif>";}
			if($PaisG1 == '155'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/155.gif>";}
			if($PaisG1 == '156'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/156.gif>";}
			if($PaisG1 == '157'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/157.gif>";}
			if($PaisG1 == '158'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/158.gif>";}
			if($PaisG1 == '159'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/159.gif>";}
			if($PaisG1 == '160'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/160.gif>";}
			if($PaisG1 == '161'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/161.gif>";}
			if($PaisG1 == '162'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/162.gif>";}
			if($PaisG1 == '163'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/163.gif>";}
			if($PaisG1 == '164'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/164.gif>";}
			if($PaisG1 == '165'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/165.gif>";}
			if($PaisG1 == '166'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/166.gif>";}
			if($PaisG1 == '167'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/167.gif>";}
			if($PaisG1 == '168'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/168.gif>";}
			if($PaisG1 == '169'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/169.gif>";}
			if($PaisG1 == '170'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/170.gif>";}
			if($PaisG1 == '171'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/171.gif>";}
			if($PaisG1 == '172'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/172.gif>";}
			if($PaisG1 == '173'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/173.gif>";}
			if($PaisG1 == '174'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/174.gif>";}
			if($PaisG1 == '175'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/175.gif>";}
			if($PaisG1 == '176'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/176.gif>";}
			if($PaisG1 == '177'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/177.gif>";}
			if($PaisG1 == '178'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/178.gif>";}
			if($PaisG1 == '179'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/179.gif>";}
			if($PaisG1 == '180'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/180.gif>";}
			if($PaisG1 == '181'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/181.gif>";}
			if($PaisG1 == '182'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/182.gif>";}
			if($PaisG1 == '183'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/183.gif>";}
			if($PaisG1 == '184'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/184.gif>";}
			if($PaisG1 == '185'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/185.gif>";}
			if($PaisG1 == '186'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/186.gif>";}
			if($PaisG1 == '187'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/187.gif>";}
			if($PaisG1 == '188'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/188.gif>";}
			if($PaisG1 == '189'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/189.gif>";}
			if($PaisG1 == '190'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/190.gif>";}
			if($PaisG1 == '191'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/191.gif>";}
			if($PaisG1 == '192'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/192.gif>";}
			if($PaisG1 == '193'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/193.gif>";}
			if($PaisG1 == '194'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/194.gif>";}
			if($PaisG1 == '195'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/195.gif>";}
			if($PaisG1 == '196'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/196.gif>";}
			if($PaisG1 == '197'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/197.gif>";}
			if($PaisG1 == '198'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/198.gif>";}
			if($PaisG1 == '199'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/199.gif>";}
			if($PaisG1 == '200'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/200.gif>";}
			if($PaisG1 == '201'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/201.gif>";}
			if($PaisG1 == '202'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/202.gif>";}
			if($PaisG1 == '203'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/203.gif>";}
			if($PaisG1 == '204'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/204.gif>";}
			if($PaisG1 == '205'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/205.gif>";}
			if($PaisG1 == '206'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/206.gif>";}
			if($PaisG1 == '207'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/207.gif>";}
			if($PaisG1 == '208'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/208.gif>";}
			if($PaisG1 == '209'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/209.gif>";}
			if($PaisG1 == '210'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/210.gif>";}
			if($PaisG1 == '211'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/211.gif>";}
			if($PaisG1 == '212'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/212.gif>";}
			if($PaisG1 == '213'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/213.gif>";}
			if($PaisG1 == '214'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/214.gif>";}
			if($PaisG1 == '215'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/215.gif>";}
			if($PaisG1 == '216'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/216.gif>";}
			if($PaisG1 == '217'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/217.gif>";}
			if($PaisG1 == '218'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/218.gif>";}
			if($PaisG1 == '219'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/219.gif>";}
			if($PaisG1 == '220'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/220.gif>";}
			if($PaisG1 == '221'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/221.gif>";}
			if($PaisG1 == '222'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/222.gif>";}
			if($PaisG1 == '223'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/223.gif>";}
			if($PaisG1 == '224'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/224.gif>";}
			if($PaisG1 == '225'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/225.gif>";}
			if($PaisG1 == '226'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/226.gif>";}
			if($PaisG1 == '227'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/227.gif>";}
			if($PaisG1 == '228'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/228.gif>";}
			if($PaisG1 == '229'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/229.gif>";}
			if($PaisG1 == '230'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/230.gif>";}
			if($PaisG1 == '231'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/231.gif>";}
			if($PaisG1 == '232'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/232.gif>";}
			if($PaisG1 == '233'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/233.gif>";}
			if($PaisG1 == '234'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/234.gif>";}
			if($PaisG1 == '235'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/235.gif>";}
			if($PaisG1 == '236'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/236.gif>";}
			if($PaisG1 == '237'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/237.gif>";}
			if($PaisG1 == '238'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/238.gif>";}
			if($PaisG1 == '239'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/239.gif>";}
			if($PaisG1 == '240'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/240.gif>";}
			if($PaisG1 == '241'){ $PaisG1 ="<img src=template/".$core['config']['template']."/images/flags/241.gif>";}
			
			if($PaisG2 == '1'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/1.gif>";}
			if($PaisG2 == '2'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/2.gif>";}
			if($PaisG2 == '3'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/3.gif>";}
			if($PaisG2 == '4'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/4.gif>";}
			if($PaisG2 == '5'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/5.gif>";}
			if($PaisG2 == '6'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/6.gif>";}
			if($PaisG2 == '7'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/7.gif>";}
			if($PaisG2 == '8'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/8.gif>";}
			if($PaisG2 == '9'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/9.gif>";}
			if($PaisG2 == '10'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/10.gif>";}
			if($PaisG2 == '11'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/11.gif>";}
			if($PaisG2 == '12'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/12.gif>";}
			if($PaisG2 == '13'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/13.gif>";}
			if($PaisG2 == '14'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/14.gif>";}
			if($PaisG2 == '15'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/15.gif>";}
			if($PaisG2 == '16'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/16.gif>";}
			if($PaisG2 == '17'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/17.gif>";}
			if($PaisG2 == '18'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/18.gif>";}
			if($PaisG2 == '19'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/19.gif>";}
			if($PaisG2 == '20'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/20.gif>";}
			if($PaisG2 == '21'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/21.gif>";}
			if($PaisG2 == '22'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/22.gif>";}
			if($PaisG2 == '23'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/23.gif>";}
			if($PaisG2 == '24'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/24.gif>";}
			if($PaisG2 == '25'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/25.gif>";}
			if($PaisG2 == '26'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/26.gif>";}
			if($PaisG2 == '27'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/27.gif>";}
			if($PaisG2 == '28'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/28.gif>";}
			if($PaisG2 == '29'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/29.gif>";}
			if($PaisG2 == '30'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/30.gif>";}
			if($PaisG2 == '31'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/31.gif>";}
			if($PaisG2 == '32'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/32.gif>";}
			if($PaisG2 == '33'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/33.gif>";}
			if($PaisG2 == '34'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/34.gif>";}
			if($PaisG2 == '35'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/35.gif>";}
			if($PaisG2 == '36'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/36.gif>";}
			if($PaisG2 == '37'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/37.gif>";}
			if($PaisG2 == '38'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/38.gif>";}
			if($PaisG2 == '39'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/39.gif>";}
			if($PaisG2 == '40'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/40.gif>";}
			if($PaisG2 == '41'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/41.gif>";}
			if($PaisG2 == '42'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/42.gif>";}
			if($PaisG2 == '43'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/43.gif>";}
			if($PaisG2 == '44'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/44.gif>";}
			if($PaisG2 == '45'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/45.gif>";}
			if($PaisG2 == '46'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/46.gif>";}
			if($PaisG2 == '47'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/47.gif>";}
			if($PaisG2 == '48'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/48.gif>";}
			if($PaisG2 == '49'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/49.gif>";}
			if($PaisG2 == '50'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/50.gif>";}
			if($PaisG2 == '51'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/51.gif>";}
			if($PaisG2 == '52'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/52.gif>";}
			if($PaisG2 == '53'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/53.gif>";}
			if($PaisG2 == '54'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/54.gif>";}
			if($PaisG2 == '55'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/55.gif>";}
			if($PaisG2 == '56'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/56.gif>";}
			if($PaisG2 == '57'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/57.gif>";}
			if($PaisG2 == '58'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/58.gif>";}
			if($PaisG2 == '59'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/59.gif>";}
			if($PaisG2 == '60'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/60.gif>";}
			if($PaisG2 == '61'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/61.gif>";}
			if($PaisG2 == '62'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/62.gif>";}
			if($PaisG2 == '63'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/63.gif>";}
			if($PaisG2 == '64'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/64.gif>";}
			if($PaisG2 == '65'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/65.gif>";}
			if($PaisG2 == '66'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/66.gif>";}
			if($PaisG2 == '67'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/67.gif>";}
			if($PaisG2 == '68'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/68.gif>";}
			if($PaisG2 == '69'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/69.gif>";}
			if($PaisG2 == '70'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/70.gif>";}
			if($PaisG2 == '71'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/71.gif>";}
			if($PaisG2 == '72'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/72.gif>";}
			if($PaisG2 == '73'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/73.gif>";}
			if($PaisG2 == '74'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/74.gif>";}
			if($PaisG2 == '75'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/75.gif>";}
			if($PaisG2 == '76'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/76.gif>";}
			if($PaisG2 == '77'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/77.gif>";}
			if($PaisG2 == '78'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/78.gif>";}
			if($PaisG2 == '79'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/79.gif>";}
			if($PaisG2 == '80'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/80.gif>";}
			if($PaisG2 == '81'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/81.gif>";}
			if($PaisG2 == '82'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/82.gif>";}
			if($PaisG2 == '83'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/83.gif>";}
			if($PaisG2 == '84'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/84.gif>";}
			if($PaisG2 == '85'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/85.gif>";}
			if($PaisG2 == '86'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/86.gif>";}
			if($PaisG2 == '87'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/87.gif>";}
			if($PaisG2 == '88'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/88.gif>";}
			if($PaisG2 == '89'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/89.gif>";}
			if($PaisG2 == '90'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/90.gif>";}
			if($PaisG2 == '91'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/91.gif>";}
			if($PaisG2 == '92'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/92.gif>";}
			if($PaisG2 == '93'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/93.gif>";}
			if($PaisG2 == '94'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/94.gif>";}
			if($PaisG2 == '95'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/95.gif>";}
			if($PaisG2 == '96'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/96.gif>";}
			if($PaisG2 == '97'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/97.gif>";}
			if($PaisG2 == '98'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/98.gif>";}
			if($PaisG2 == '99'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/99.gif>";}
			if($PaisG2 == '100'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/100.gif>";}
			if($PaisG2 == '101'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/101.gif>";}
			if($PaisG2 == '102'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/102.gif>";}
			if($PaisG2 == '103'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/103.gif>";}
			if($PaisG2 == '104'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/104.gif>";}
			if($PaisG2 == '105'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/105.gif>";}
			if($PaisG2 == '106'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/106.gif>";}
			if($PaisG2 == '107'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/107.gif>";}
			if($PaisG2 == '108'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/108.gif>";}
			if($PaisG2 == '109'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/109.gif>";}
			if($PaisG2 == '110'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/110.gif>";}
			if($PaisG2 == '111'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/111.gif>";}
			if($PaisG2 == '112'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/112.gif>";}
			if($PaisG2 == '113'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/113.gif>";}
			if($PaisG2 == '114'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/114.gif>";}
			if($PaisG2 == '115'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/115.gif>";}
			if($PaisG2 == '116'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/116.gif>";}
			if($PaisG2 == '117'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/117.gif>";}
			if($PaisG2 == '118'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/118.gif>";}
			if($PaisG2 == '119'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/119.gif>";}
			if($PaisG2 == '120'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/120.gif>";}
			if($PaisG2 == '121'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/121.gif>";}
			if($PaisG2 == '122'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/122.gif>";}
			if($PaisG2 == '123'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/123.gif>";}
			if($PaisG2 == '124'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/124.gif>";}
			if($PaisG2 == '125'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/125.gif>";}
			if($PaisG2 == '126'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/126.gif>";}
			if($PaisG2 == '127'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/127.gif>";}
			if($PaisG2 == '128'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/128.gif>";}
			if($PaisG2 == '129'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/129.gif>";}
			if($PaisG2 == '130'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/130.gif>";}
			if($PaisG2 == '131'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/131.gif>";}
			if($PaisG2 == '132'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/132.gif>";}
			if($PaisG2 == '133'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/133.gif>";}
			if($PaisG2 == '134'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/134.gif>";}
			if($PaisG2 == '135'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/135.gif>";}
			if($PaisG2 == '136'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/136.gif>";}
			if($PaisG2 == '137'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/137.gif>";}
			if($PaisG2 == '138'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/138.gif>";}
			if($PaisG2 == '139'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/139.gif>";}
			if($PaisG2 == '140'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/140.gif>";}
			if($PaisG2 == '141'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/141.gif>";}
			if($PaisG2 == '142'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/142.gif>";}
			if($PaisG2 == '143'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/143.gif>";}
			if($PaisG2 == '144'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/144.gif>";}
			if($PaisG2 == '145'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/145.gif>";}
			if($PaisG2 == '146'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/146.gif>";}
			if($PaisG2 == '147'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/147.gif>";}
			if($PaisG2 == '148'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/148.gif>";}
			if($PaisG2 == '149'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/149.gif>";}
			if($PaisG2 == '150'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/150.gif>";}
			if($PaisG2 == '151'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/151.gif>";}
			if($PaisG2 == '152'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/152.gif>";}
			if($PaisG2 == '153'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/153.gif>";}
			if($PaisG2 == '154'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/154.gif>";}
			if($PaisG2 == '155'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/155.gif>";}
			if($PaisG2 == '156'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/156.gif>";}
			if($PaisG2 == '157'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/157.gif>";}
			if($PaisG2 == '158'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/158.gif>";}
			if($PaisG2 == '159'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/159.gif>";}
			if($PaisG2 == '160'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/160.gif>";}
			if($PaisG2 == '161'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/161.gif>";}
			if($PaisG2 == '162'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/162.gif>";}
			if($PaisG2 == '163'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/163.gif>";}
			if($PaisG2 == '164'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/164.gif>";}
			if($PaisG2 == '165'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/165.gif>";}
			if($PaisG2 == '166'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/166.gif>";}
			if($PaisG2 == '167'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/167.gif>";}
			if($PaisG2 == '168'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/168.gif>";}
			if($PaisG2 == '169'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/169.gif>";}
			if($PaisG2 == '170'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/170.gif>";}
			if($PaisG2 == '171'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/171.gif>";}
			if($PaisG2 == '172'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/172.gif>";}
			if($PaisG2 == '173'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/173.gif>";}
			if($PaisG2 == '174'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/174.gif>";}
			if($PaisG2 == '175'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/175.gif>";}
			if($PaisG2 == '176'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/176.gif>";}
			if($PaisG2 == '177'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/177.gif>";}
			if($PaisG2 == '178'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/178.gif>";}
			if($PaisG2 == '179'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/179.gif>";}
			if($PaisG2 == '180'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/180.gif>";}
			if($PaisG2 == '181'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/181.gif>";}
			if($PaisG2 == '182'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/182.gif>";}
			if($PaisG2 == '183'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/183.gif>";}
			if($PaisG2 == '184'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/184.gif>";}
			if($PaisG2 == '185'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/185.gif>";}
			if($PaisG2 == '186'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/186.gif>";}
			if($PaisG2 == '187'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/187.gif>";}
			if($PaisG2 == '188'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/188.gif>";}
			if($PaisG2 == '189'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/189.gif>";}
			if($PaisG2 == '190'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/190.gif>";}
			if($PaisG2 == '191'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/191.gif>";}
			if($PaisG2 == '192'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/192.gif>";}
			if($PaisG2 == '193'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/193.gif>";}
			if($PaisG2 == '194'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/194.gif>";}
			if($PaisG2 == '195'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/195.gif>";}
			if($PaisG2 == '196'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/196.gif>";}
			if($PaisG2 == '197'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/197.gif>";}
			if($PaisG2 == '198'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/198.gif>";}
			if($PaisG2 == '199'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/199.gif>";}
			if($PaisG2 == '200'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/200.gif>";}
			if($PaisG2 == '201'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/201.gif>";}
			if($PaisG2 == '202'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/202.gif>";}
			if($PaisG2 == '203'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/203.gif>";}
			if($PaisG2 == '204'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/204.gif>";}
			if($PaisG2 == '205'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/205.gif>";}
			if($PaisG2 == '206'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/206.gif>";}
			if($PaisG2 == '207'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/207.gif>";}
			if($PaisG2 == '208'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/208.gif>";}
			if($PaisG2 == '209'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/209.gif>";}
			if($PaisG2 == '210'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/210.gif>";}
			if($PaisG2 == '211'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/211.gif>";}
			if($PaisG2 == '212'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/212.gif>";}
			if($PaisG2 == '213'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/213.gif>";}
			if($PaisG2 == '214'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/214.gif>";}
			if($PaisG2 == '215'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/215.gif>";}
			if($PaisG2 == '216'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/216.gif>";}
			if($PaisG2 == '217'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/217.gif>";}
			if($PaisG2 == '218'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/218.gif>";}
			if($PaisG2 == '219'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/219.gif>";}
			if($PaisG2 == '220'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/220.gif>";}
			if($PaisG2 == '221'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/221.gif>";}
			if($PaisG2 == '222'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/222.gif>";}
			if($PaisG2 == '223'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/223.gif>";}
			if($PaisG2 == '224'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/224.gif>";}
			if($PaisG2 == '225'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/225.gif>";}
			if($PaisG2 == '226'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/226.gif>";}
			if($PaisG2 == '227'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/227.gif>";}
			if($PaisG2 == '228'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/228.gif>";}
			if($PaisG2 == '229'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/229.gif>";}
			if($PaisG2 == '230'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/230.gif>";}
			if($PaisG2 == '231'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/231.gif>";}
			if($PaisG2 == '232'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/232.gif>";}
			if($PaisG2 == '233'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/233.gif>";}
			if($PaisG2 == '234'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/234.gif>";}
			if($PaisG2 == '235'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/235.gif>";}
			if($PaisG2 == '236'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/236.gif>";}
			if($PaisG2 == '237'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/237.gif>";}
			if($PaisG2 == '238'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/238.gif>";}
			if($PaisG2 == '239'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/239.gif>";}
			if($PaisG2 == '240'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/240.gif>";}
			if($PaisG2 == '241'){ $PaisG2 ="<img src=template/".$core['config']['template']."/images/flags/241.gif>";}
			
			if($PaisG3 == '1'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/1.gif>";}
			if($PaisG3 == '2'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/2.gif>";}
			if($PaisG3 == '3'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/3.gif>";}
			if($PaisG3 == '4'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/4.gif>";}
			if($PaisG3 == '5'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/5.gif>";}
			if($PaisG3 == '6'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/6.gif>";}
			if($PaisG3 == '7'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/7.gif>";}
			if($PaisG3 == '8'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/8.gif>";}
			if($PaisG3 == '9'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/9.gif>";}
			if($PaisG3 == '10'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/10.gif>";}
			if($PaisG3 == '11'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/11.gif>";}
			if($PaisG3 == '12'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/12.gif>";}
			if($PaisG3 == '13'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/13.gif>";}
			if($PaisG3 == '14'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/14.gif>";}
			if($PaisG3 == '15'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/15.gif>";}
			if($PaisG3 == '16'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/16.gif>";}
			if($PaisG3 == '17'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/17.gif>";}
			if($PaisG3 == '18'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/18.gif>";}
			if($PaisG3 == '19'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/19.gif>";}
			if($PaisG3 == '20'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/20.gif>";}
			if($PaisG3 == '21'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/21.gif>";}
			if($PaisG3 == '22'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/22.gif>";}
			if($PaisG3 == '23'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/23.gif>";}
			if($PaisG3 == '24'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/24.gif>";}
			if($PaisG3 == '25'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/25.gif>";}
			if($PaisG3 == '26'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/26.gif>";}
			if($PaisG3 == '27'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/27.gif>";}
			if($PaisG3 == '28'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/28.gif>";}
			if($PaisG3 == '29'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/29.gif>";}
			if($PaisG3 == '30'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/30.gif>";}
			if($PaisG3 == '31'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/31.gif>";}
			if($PaisG3 == '32'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/32.gif>";}
			if($PaisG3 == '33'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/33.gif>";}
			if($PaisG3 == '34'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/34.gif>";}
			if($PaisG3 == '35'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/35.gif>";}
			if($PaisG3 == '36'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/36.gif>";}
			if($PaisG3 == '37'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/37.gif>";}
			if($PaisG3 == '38'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/38.gif>";}
			if($PaisG3 == '39'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/39.gif>";}
			if($PaisG3 == '40'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/40.gif>";}
			if($PaisG3 == '41'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/41.gif>";}
			if($PaisG3 == '42'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/42.gif>";}
			if($PaisG3 == '43'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/43.gif>";}
			if($PaisG3 == '44'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/44.gif>";}
			if($PaisG3 == '45'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/45.gif>";}
			if($PaisG3 == '46'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/46.gif>";}
			if($PaisG3 == '47'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/47.gif>";}
			if($PaisG3 == '48'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/48.gif>";}
			if($PaisG3 == '49'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/49.gif>";}
			if($PaisG3 == '50'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/50.gif>";}
			if($PaisG3 == '51'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/51.gif>";}
			if($PaisG3 == '52'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/52.gif>";}
			if($PaisG3 == '53'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/53.gif>";}
			if($PaisG3 == '54'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/54.gif>";}
			if($PaisG3 == '55'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/55.gif>";}
			if($PaisG3 == '56'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/56.gif>";}
			if($PaisG3 == '57'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/57.gif>";}
			if($PaisG3 == '58'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/58.gif>";}
			if($PaisG3 == '59'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/59.gif>";}
			if($PaisG3 == '60'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/60.gif>";}
			if($PaisG3 == '61'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/61.gif>";}
			if($PaisG3 == '62'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/62.gif>";}
			if($PaisG3 == '63'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/63.gif>";}
			if($PaisG3 == '64'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/64.gif>";}
			if($PaisG3 == '65'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/65.gif>";}
			if($PaisG3 == '66'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/66.gif>";}
			if($PaisG3 == '67'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/67.gif>";}
			if($PaisG3 == '68'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/68.gif>";}
			if($PaisG3 == '69'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/69.gif>";}
			if($PaisG3 == '70'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/70.gif>";}
			if($PaisG3 == '71'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/71.gif>";}
			if($PaisG3 == '72'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/72.gif>";}
			if($PaisG3 == '73'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/73.gif>";}
			if($PaisG3 == '74'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/74.gif>";}
			if($PaisG3 == '75'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/75.gif>";}
			if($PaisG3 == '76'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/76.gif>";}
			if($PaisG3 == '77'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/77.gif>";}
			if($PaisG3 == '78'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/78.gif>";}
			if($PaisG3 == '79'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/79.gif>";}
			if($PaisG3 == '80'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/80.gif>";}
			if($PaisG3 == '81'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/81.gif>";}
			if($PaisG3 == '82'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/82.gif>";}
			if($PaisG3 == '83'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/83.gif>";}
			if($PaisG3 == '84'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/84.gif>";}
			if($PaisG3 == '85'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/85.gif>";}
			if($PaisG3 == '86'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/86.gif>";}
			if($PaisG3 == '87'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/87.gif>";}
			if($PaisG3 == '88'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/88.gif>";}
			if($PaisG3 == '89'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/89.gif>";}
			if($PaisG3 == '90'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/90.gif>";}
			if($PaisG3 == '91'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/91.gif>";}
			if($PaisG3 == '92'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/92.gif>";}
			if($PaisG3 == '93'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/93.gif>";}
			if($PaisG3 == '94'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/94.gif>";}
			if($PaisG3 == '95'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/95.gif>";}
			if($PaisG3 == '96'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/96.gif>";}
			if($PaisG3 == '97'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/97.gif>";}
			if($PaisG3 == '98'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/98.gif>";}
			if($PaisG3 == '99'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/99.gif>";}
			if($PaisG3 == '100'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/100.gif>";}
			if($PaisG3 == '101'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/101.gif>";}
			if($PaisG3 == '102'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/102.gif>";}
			if($PaisG3 == '103'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/103.gif>";}
			if($PaisG3 == '104'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/104.gif>";}
			if($PaisG3 == '105'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/105.gif>";}
			if($PaisG3 == '106'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/106.gif>";}
			if($PaisG3 == '107'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/107.gif>";}
			if($PaisG3 == '108'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/108.gif>";}
			if($PaisG3 == '109'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/109.gif>";}
			if($PaisG3 == '110'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/110.gif>";}
			if($PaisG3 == '111'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/111.gif>";}
			if($PaisG3 == '112'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/112.gif>";}
			if($PaisG3 == '113'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/113.gif>";}
			if($PaisG3 == '114'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/114.gif>";}
			if($PaisG3 == '115'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/115.gif>";}
			if($PaisG3 == '116'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/116.gif>";}
			if($PaisG3 == '117'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/117.gif>";}
			if($PaisG3 == '118'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/118.gif>";}
			if($PaisG3 == '119'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/119.gif>";}
			if($PaisG3 == '120'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/120.gif>";}
			if($PaisG3 == '121'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/121.gif>";}
			if($PaisG3 == '122'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/122.gif>";}
			if($PaisG3 == '123'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/123.gif>";}
			if($PaisG3 == '124'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/124.gif>";}
			if($PaisG3 == '125'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/125.gif>";}
			if($PaisG3 == '126'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/126.gif>";}
			if($PaisG3 == '127'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/127.gif>";}
			if($PaisG3 == '128'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/128.gif>";}
			if($PaisG3 == '129'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/129.gif>";}
			if($PaisG3 == '130'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/130.gif>";}
			if($PaisG3 == '131'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/131.gif>";}
			if($PaisG3 == '132'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/132.gif>";}
			if($PaisG3 == '133'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/133.gif>";}
			if($PaisG3 == '134'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/134.gif>";}
			if($PaisG3 == '135'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/135.gif>";}
			if($PaisG3 == '136'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/136.gif>";}
			if($PaisG3 == '137'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/137.gif>";}
			if($PaisG3 == '138'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/138.gif>";}
			if($PaisG3 == '139'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/139.gif>";}
			if($PaisG3 == '140'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/140.gif>";}
			if($PaisG3 == '141'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/141.gif>";}
			if($PaisG3 == '142'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/142.gif>";}
			if($PaisG3 == '143'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/143.gif>";}
			if($PaisG3 == '144'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/144.gif>";}
			if($PaisG3 == '145'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/145.gif>";}
			if($PaisG3 == '146'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/146.gif>";}
			if($PaisG3 == '147'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/147.gif>";}
			if($PaisG3 == '148'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/148.gif>";}
			if($PaisG3 == '149'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/149.gif>";}
			if($PaisG3 == '150'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/150.gif>";}
			if($PaisG3 == '151'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/151.gif>";}
			if($PaisG3 == '152'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/152.gif>";}
			if($PaisG3 == '153'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/153.gif>";}
			if($PaisG3 == '154'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/154.gif>";}
			if($PaisG3 == '155'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/155.gif>";}
			if($PaisG3 == '156'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/156.gif>";}
			if($PaisG3 == '157'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/157.gif>";}
			if($PaisG3 == '158'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/158.gif>";}
			if($PaisG3 == '159'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/159.gif>";}
			if($PaisG3 == '160'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/160.gif>";}
			if($PaisG3 == '161'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/161.gif>";}
			if($PaisG3 == '162'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/162.gif>";}
			if($PaisG3 == '163'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/163.gif>";}
			if($PaisG3 == '164'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/164.gif>";}
			if($PaisG3 == '165'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/165.gif>";}
			if($PaisG3 == '166'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/166.gif>";}
			if($PaisG3 == '167'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/167.gif>";}
			if($PaisG3 == '168'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/168.gif>";}
			if($PaisG3 == '169'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/169.gif>";}
			if($PaisG3 == '170'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/170.gif>";}
			if($PaisG3 == '171'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/171.gif>";}
			if($PaisG3 == '172'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/172.gif>";}
			if($PaisG3 == '173'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/173.gif>";}
			if($PaisG3 == '174'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/174.gif>";}
			if($PaisG3 == '175'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/175.gif>";}
			if($PaisG3 == '176'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/176.gif>";}
			if($PaisG3 == '177'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/177.gif>";}
			if($PaisG3 == '178'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/178.gif>";}
			if($PaisG3 == '179'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/179.gif>";}
			if($PaisG3 == '180'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/180.gif>";}
			if($PaisG3 == '181'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/181.gif>";}
			if($PaisG3 == '182'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/182.gif>";}
			if($PaisG3 == '183'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/183.gif>";}
			if($PaisG3 == '184'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/184.gif>";}
			if($PaisG3 == '185'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/185.gif>";}
			if($PaisG3 == '186'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/186.gif>";}
			if($PaisG3 == '187'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/187.gif>";}
			if($PaisG3 == '188'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/188.gif>";}
			if($PaisG3 == '189'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/189.gif>";}
			if($PaisG3 == '190'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/190.gif>";}
			if($PaisG3 == '191'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/191.gif>";}
			if($PaisG3 == '192'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/192.gif>";}
			if($PaisG3 == '193'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/193.gif>";}
			if($PaisG3 == '194'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/194.gif>";}
			if($PaisG3 == '195'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/195.gif>";}
			if($PaisG3 == '196'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/196.gif>";}
			if($PaisG3 == '197'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/197.gif>";}
			if($PaisG3 == '198'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/198.gif>";}
			if($PaisG3 == '199'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/199.gif>";}
			if($PaisG3 == '200'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/200.gif>";}
			if($PaisG3 == '201'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/201.gif>";}
			if($PaisG3 == '202'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/202.gif>";}
			if($PaisG3 == '203'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/203.gif>";}
			if($PaisG3 == '204'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/204.gif>";}
			if($PaisG3 == '205'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/205.gif>";}
			if($PaisG3 == '206'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/206.gif>";}
			if($PaisG3 == '207'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/207.gif>";}
			if($PaisG3 == '208'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/208.gif>";}
			if($PaisG3 == '209'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/209.gif>";}
			if($PaisG3 == '210'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/210.gif>";}
			if($PaisG3 == '211'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/211.gif>";}
			if($PaisG3 == '212'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/212.gif>";}
			if($PaisG3 == '213'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/213.gif>";}
			if($PaisG3 == '214'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/214.gif>";}
			if($PaisG3 == '215'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/215.gif>";}
			if($PaisG3 == '216'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/216.gif>";}
			if($PaisG3 == '217'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/217.gif>";}
			if($PaisG3 == '218'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/218.gif>";}
			if($PaisG3 == '219'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/219.gif>";}
			if($PaisG3 == '220'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/220.gif>";}
			if($PaisG3 == '221'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/221.gif>";}
			if($PaisG3 == '222'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/222.gif>";}
			if($PaisG3 == '223'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/223.gif>";}
			if($PaisG3 == '224'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/224.gif>";}
			if($PaisG3 == '225'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/225.gif>";}
			if($PaisG3 == '226'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/226.gif>";}
			if($PaisG3 == '227'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/227.gif>";}
			if($PaisG3 == '228'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/228.gif>";}
			if($PaisG3 == '229'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/229.gif>";}
			if($PaisG3 == '230'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/230.gif>";}
			if($PaisG3 == '231'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/231.gif>";}
			if($PaisG3 == '232'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/232.gif>";}
			if($PaisG3 == '233'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/233.gif>";}
			if($PaisG3 == '234'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/234.gif>";}
			if($PaisG3 == '235'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/235.gif>";}
			if($PaisG3 == '236'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/236.gif>";}
			if($PaisG3 == '237'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/237.gif>";}
			if($PaisG3 == '238'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/238.gif>";}
			if($PaisG3 == '239'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/239.gif>";}
			if($PaisG3 == '240'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/240.gif>";}
			if($PaisG3 == '241'){ $PaisG3 ="<img src=template/".$core['config']['template']."/images/flags/241.gif>";}
?>